name: ai-benchmarker
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - conda-forge::transformers
  - conda-forge::huggingface_hub
  - conda-forge::peft
  - conda-forge::trl
  - conda-forge::psutil
  - conda-forge::accelerate
  - conda-forge::tqdm
  - conda-forge::matplotlib
  - conda-forge::pandas
  - conda-forge::numpy
  - conda-forge::pip
  - conda-forge::pynvml
  - pip:
    - datasets
    - optimum
    - speechbrain
    - evaluate==0.4.3
    - bitsandbytes
    #- torch==2.2.5 --index-url https://download.pytorch.org/whl/cu121
    #- torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cu121
    #- torchaudio==2.2.5 --index-url https://download.pytorch.org/whl/cu121