name: ai-benchmarker
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - conda-forge::huggingface_hub
  - conda-forge::datasets
  - conda-forge::peft
  - conda-forge::trl
  - conda-forge::psutil
  - conda-forge::accelerate
  - conda-forge::tqdm
  - conda-forge::matplotlib
  - conda-forge::pandas
  - conda-forge::numpy
  - conda-forge::transformers
  - conda-forge::pip
  - conda-forge::pynvml
  - pip:
    - evaluate==0.4.3
    - speechbrain